version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:8000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5500:80'
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - backend